services:
  site:
    image: klakegg/hugo:0.120.0-ext-alpine
    build:
      context: .
    command: server --bind 0.0.0.0
    ports:
      - "1313:1313"
    volumes:
      - .:/src
    working_dir: /src
